# Generated by Django 2.2 on 2021-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211020_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='referee_id',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
