# Generated by Django 2.2 on 2021-10-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211020_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='referee_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
    ]
