# Generated by Django 2.2 on 2021-10-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20211020_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
    ]
